// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package testbootstrap

import (
	"context"
	"encoding/json"
	"time"

	"github.com/Khan/genqlient/graphql"
	"github.com/oapi-codegen/nullable"
)

type ActivateWorkspaceInput struct {
	// Deprecated: the workspace name is set at creation (signUpInNewWorkspace) and this field is ignored during activation. Kept for backward compatibility.
	DisplayName nullable.Nullable[string] `json:"displayName,omitempty"`
}

// GetDisplayName returns ActivateWorkspaceInput.DisplayName, and is useful for accessing the field via an interface.
func (v *ActivateWorkspaceInput) GetDisplayName() nullable.Nullable[string] { return v.DisplayName }

// BootstrapAccess includes the GraphQL fields of AvailableWorkspacesAndAccessTokens requested by the fragment BootstrapAccess.
type BootstrapAccess struct {
	Tokens              BootstrapAccessTokensAuthTokenPair `json:"tokens"`
	AvailableWorkspaces BootstrapAccessAvailableWorkspaces `json:"availableWorkspaces"`
}

// GetTokens returns BootstrapAccess.Tokens, and is useful for accessing the field via an interface.
func (v *BootstrapAccess) GetTokens() BootstrapAccessTokensAuthTokenPair { return v.Tokens }

// GetAvailableWorkspaces returns BootstrapAccess.AvailableWorkspaces, and is useful for accessing the field via an interface.
func (v *BootstrapAccess) GetAvailableWorkspaces() BootstrapAccessAvailableWorkspaces {
	return v.AvailableWorkspaces
}

// BootstrapAccessAvailableWorkspaces includes the requested fields of the GraphQL type AvailableWorkspaces.
type BootstrapAccessAvailableWorkspaces struct {
	AvailableWorkspacesForSignIn []BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace `json:"availableWorkspacesForSignIn"`
	AvailableWorkspacesForSignUp []BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace `json:"availableWorkspacesForSignUp"`
}

// GetAvailableWorkspacesForSignIn returns BootstrapAccessAvailableWorkspaces.AvailableWorkspacesForSignIn, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspaces) GetAvailableWorkspacesForSignIn() []BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace {
	return v.AvailableWorkspacesForSignIn
}

// GetAvailableWorkspacesForSignUp returns BootstrapAccessAvailableWorkspaces.AvailableWorkspacesForSignUp, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspaces) GetAvailableWorkspacesForSignUp() []BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace {
	return v.AvailableWorkspacesForSignUp
}

// BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace includes the requested fields of the GraphQL type AvailableWorkspace.
type BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace struct {
	Id            string                                                                                        `json:"id"`
	DisplayName   nullable.Nullable[string]                                                                     `json:"displayName"`
	WorkspaceUrls BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls `json:"workspaceUrls"`
}

// GetId returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace.Id, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace) GetId() string {
	return v.Id
}

// GetDisplayName returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace.DisplayName, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace) GetDisplayName() nullable.Nullable[string] {
	return v.DisplayName
}

// GetWorkspaceUrls returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace.WorkspaceUrls, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspace) GetWorkspaceUrls() BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls {
	return v.WorkspaceUrls
}

// BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls includes the requested fields of the GraphQL type WorkspaceUrls.
type BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls struct {
	CustomUrl    nullable.Nullable[string] `json:"customUrl"`
	SubdomainUrl string                    `json:"subdomainUrl"`
}

// GetCustomUrl returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls.CustomUrl, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls) GetCustomUrl() nullable.Nullable[string] {
	return v.CustomUrl
}

// GetSubdomainUrl returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls.SubdomainUrl, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignInAvailableWorkspaceWorkspaceUrls) GetSubdomainUrl() string {
	return v.SubdomainUrl
}

// BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace includes the requested fields of the GraphQL type AvailableWorkspace.
type BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace struct {
	Id            string                                                                                        `json:"id"`
	DisplayName   nullable.Nullable[string]                                                                     `json:"displayName"`
	WorkspaceUrls BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls `json:"workspaceUrls"`
}

// GetId returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace.Id, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace) GetId() string {
	return v.Id
}

// GetDisplayName returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace.DisplayName, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace) GetDisplayName() nullable.Nullable[string] {
	return v.DisplayName
}

// GetWorkspaceUrls returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace.WorkspaceUrls, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspace) GetWorkspaceUrls() BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls {
	return v.WorkspaceUrls
}

// BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls includes the requested fields of the GraphQL type WorkspaceUrls.
type BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls struct {
	CustomUrl    nullable.Nullable[string] `json:"customUrl"`
	SubdomainUrl string                    `json:"subdomainUrl"`
}

// GetCustomUrl returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls.CustomUrl, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls) GetCustomUrl() nullable.Nullable[string] {
	return v.CustomUrl
}

// GetSubdomainUrl returns BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls.SubdomainUrl, and is useful for accessing the field via an interface.
func (v *BootstrapAccessAvailableWorkspacesAvailableWorkspacesForSignUpAvailableWorkspaceWorkspaceUrls) GetSubdomainUrl() string {
	return v.SubdomainUrl
}

// BootstrapAccessTokensAuthTokenPair includes the requested fields of the GraphQL type AuthTokenPair.
type BootstrapAccessTokensAuthTokenPair struct {
	AccessOrWorkspaceAgnosticToken BootstrapToken `json:"accessOrWorkspaceAgnosticToken"`
	RefreshToken                   BootstrapToken `json:"refreshToken"`
}

// GetAccessOrWorkspaceAgnosticToken returns BootstrapAccessTokensAuthTokenPair.AccessOrWorkspaceAgnosticToken, and is useful for accessing the field via an interface.
func (v *BootstrapAccessTokensAuthTokenPair) GetAccessOrWorkspaceAgnosticToken() BootstrapToken {
	return v.AccessOrWorkspaceAgnosticToken
}

// GetRefreshToken returns BootstrapAccessTokensAuthTokenPair.RefreshToken, and is useful for accessing the field via an interface.
func (v *BootstrapAccessTokensAuthTokenPair) GetRefreshToken() BootstrapToken { return v.RefreshToken }

// Test-only onboarding for a future disposable local stack.
// Do not use these operations in provider configuration or managed resources.
type BootstrapToken struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// GetToken returns BootstrapToken.Token, and is useful for accessing the field via an interface.
func (v *BootstrapToken) GetToken() string { return v.Token }

// GetExpiresAt returns BootstrapToken.ExpiresAt, and is useful for accessing the field via an interface.
func (v *BootstrapToken) GetExpiresAt() time.Time { return v.ExpiresAt }

// BootstrapWorkspace includes the GraphQL fields of SignUp requested by the fragment BootstrapWorkspace.
type BootstrapWorkspace struct {
	LoginToken BootstrapToken                                `json:"loginToken"`
	Workspace  BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId `json:"workspace"`
}

// GetLoginToken returns BootstrapWorkspace.LoginToken, and is useful for accessing the field via an interface.
func (v *BootstrapWorkspace) GetLoginToken() BootstrapToken { return v.LoginToken }

// GetWorkspace returns BootstrapWorkspace.Workspace, and is useful for accessing the field via an interface.
func (v *BootstrapWorkspace) GetWorkspace() BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId {
	return v.Workspace
}

// BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId includes the requested fields of the GraphQL type WorkspaceUrlsAndId.
type BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId struct {
	Id            string                                                     `json:"id"`
	WorkspaceUrls BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls `json:"workspaceUrls"`
}

// GetId returns BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId.Id, and is useful for accessing the field via an interface.
func (v *BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId) GetId() string { return v.Id }

// GetWorkspaceUrls returns BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId.WorkspaceUrls, and is useful for accessing the field via an interface.
func (v *BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId) GetWorkspaceUrls() BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls {
	return v.WorkspaceUrls
}

// BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls includes the requested fields of the GraphQL type WorkspaceUrls.
type BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls struct {
	CustomUrl    nullable.Nullable[string] `json:"customUrl"`
	SubdomainUrl string                    `json:"subdomainUrl"`
}

// GetCustomUrl returns BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls.CustomUrl, and is useful for accessing the field via an interface.
func (v *BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls) GetCustomUrl() nullable.Nullable[string] {
	return v.CustomUrl
}

// GetSubdomainUrl returns BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls.SubdomainUrl, and is useful for accessing the field via an interface.
func (v *BootstrapWorkspaceWorkspaceWorkspaceUrlsAndIdWorkspaceUrls) GetSubdomainUrl() string {
	return v.SubdomainUrl
}

type SignUpInNewWorkspaceInput struct {
	DisplayName nullable.Nullable[string] `json:"displayName,omitempty"`
	Subdomain   nullable.Nullable[string] `json:"subdomain,omitempty"`
}

// GetDisplayName returns SignUpInNewWorkspaceInput.DisplayName, and is useful for accessing the field via an interface.
func (v *SignUpInNewWorkspaceInput) GetDisplayName() nullable.Nullable[string] { return v.DisplayName }

// GetSubdomain returns SignUpInNewWorkspaceInput.Subdomain, and is useful for accessing the field via an interface.
func (v *SignUpInNewWorkspaceInput) GetSubdomain() nullable.Nullable[string] { return v.Subdomain }

// TestActivateWorkspaceActivateWorkspace includes the requested fields of the GraphQL type Workspace.
type TestActivateWorkspaceActivateWorkspace struct {
	Id               string                    `json:"id"`
	DisplayName      nullable.Nullable[string] `json:"displayName"`
	ActivationStatus WorkspaceActivationStatus `json:"activationStatus"`
}

// GetId returns TestActivateWorkspaceActivateWorkspace.Id, and is useful for accessing the field via an interface.
func (v *TestActivateWorkspaceActivateWorkspace) GetId() string { return v.Id }

// GetDisplayName returns TestActivateWorkspaceActivateWorkspace.DisplayName, and is useful for accessing the field via an interface.
func (v *TestActivateWorkspaceActivateWorkspace) GetDisplayName() nullable.Nullable[string] {
	return v.DisplayName
}

// GetActivationStatus returns TestActivateWorkspaceActivateWorkspace.ActivationStatus, and is useful for accessing the field via an interface.
func (v *TestActivateWorkspaceActivateWorkspace) GetActivationStatus() WorkspaceActivationStatus {
	return v.ActivationStatus
}

// TestActivateWorkspaceResponse is returned by TestActivateWorkspace on success.
type TestActivateWorkspaceResponse struct {
	ActivateWorkspace TestActivateWorkspaceActivateWorkspace `json:"activateWorkspace"`
}

// GetActivateWorkspace returns TestActivateWorkspaceResponse.ActivateWorkspace, and is useful for accessing the field via an interface.
func (v *TestActivateWorkspaceResponse) GetActivateWorkspace() TestActivateWorkspaceActivateWorkspace {
	return v.ActivateWorkspace
}

// TestCreateWorkspaceResponse is returned by TestCreateWorkspace on success.
type TestCreateWorkspaceResponse struct {
	SignUpInNewWorkspace BootstrapWorkspace `json:"signUpInNewWorkspace"`
}

// GetSignUpInNewWorkspace returns TestCreateWorkspaceResponse.SignUpInNewWorkspace, and is useful for accessing the field via an interface.
func (v *TestCreateWorkspaceResponse) GetSignUpInNewWorkspace() BootstrapWorkspace {
	return v.SignUpInNewWorkspace
}

// TestJoinWorkspaceResponse is returned by TestJoinWorkspace on success.
type TestJoinWorkspaceResponse struct {
	SignUpInWorkspace TestJoinWorkspaceSignUpInWorkspaceSignUp `json:"signUpInWorkspace"`
}

// GetSignUpInWorkspace returns TestJoinWorkspaceResponse.SignUpInWorkspace, and is useful for accessing the field via an interface.
func (v *TestJoinWorkspaceResponse) GetSignUpInWorkspace() TestJoinWorkspaceSignUpInWorkspaceSignUp {
	return v.SignUpInWorkspace
}

// TestJoinWorkspaceSignUpInWorkspaceSignUp includes the requested fields of the GraphQL type SignUp.
type TestJoinWorkspaceSignUpInWorkspaceSignUp struct {
	BootstrapWorkspace `json:"-"`
}

// GetLoginToken returns TestJoinWorkspaceSignUpInWorkspaceSignUp.LoginToken, and is useful for accessing the field via an interface.
func (v *TestJoinWorkspaceSignUpInWorkspaceSignUp) GetLoginToken() BootstrapToken {
	return v.BootstrapWorkspace.LoginToken
}

// GetWorkspace returns TestJoinWorkspaceSignUpInWorkspaceSignUp.Workspace, and is useful for accessing the field via an interface.
func (v *TestJoinWorkspaceSignUpInWorkspaceSignUp) GetWorkspace() BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId {
	return v.BootstrapWorkspace.Workspace
}

func (v *TestJoinWorkspaceSignUpInWorkspaceSignUp) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*TestJoinWorkspaceSignUpInWorkspaceSignUp
		graphql.NoUnmarshalJSON
	}
	firstPass.TestJoinWorkspaceSignUpInWorkspaceSignUp = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.BootstrapWorkspace)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalTestJoinWorkspaceSignUpInWorkspaceSignUp struct {
	LoginToken BootstrapToken `json:"loginToken"`

	Workspace BootstrapWorkspaceWorkspaceWorkspaceUrlsAndId `json:"workspace"`
}

func (v *TestJoinWorkspaceSignUpInWorkspaceSignUp) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *TestJoinWorkspaceSignUpInWorkspaceSignUp) __premarshalJSON() (*__premarshalTestJoinWorkspaceSignUpInWorkspaceSignUp, error) {
	var retval __premarshalTestJoinWorkspaceSignUpInWorkspaceSignUp

	retval.LoginToken = v.BootstrapWorkspace.LoginToken
	retval.Workspace = v.BootstrapWorkspace.Workspace
	return &retval, nil
}

// TestSignUpResponse is returned by TestSignUp on success.
type TestSignUpResponse struct {
	SignUp TestSignUpSignUpAvailableWorkspacesAndAccessTokens `json:"signUp"`
}

// GetSignUp returns TestSignUpResponse.SignUp, and is useful for accessing the field via an interface.
func (v *TestSignUpResponse) GetSignUp() TestSignUpSignUpAvailableWorkspacesAndAccessTokens {
	return v.SignUp
}

// TestSignUpSignUpAvailableWorkspacesAndAccessTokens includes the requested fields of the GraphQL type AvailableWorkspacesAndAccessTokens.
type TestSignUpSignUpAvailableWorkspacesAndAccessTokens struct {
	BootstrapAccess `json:"-"`
}

// GetTokens returns TestSignUpSignUpAvailableWorkspacesAndAccessTokens.Tokens, and is useful for accessing the field via an interface.
func (v *TestSignUpSignUpAvailableWorkspacesAndAccessTokens) GetTokens() BootstrapAccessTokensAuthTokenPair {
	return v.BootstrapAccess.Tokens
}

// GetAvailableWorkspaces returns TestSignUpSignUpAvailableWorkspacesAndAccessTokens.AvailableWorkspaces, and is useful for accessing the field via an interface.
func (v *TestSignUpSignUpAvailableWorkspacesAndAccessTokens) GetAvailableWorkspaces() BootstrapAccessAvailableWorkspaces {
	return v.BootstrapAccess.AvailableWorkspaces
}

func (v *TestSignUpSignUpAvailableWorkspacesAndAccessTokens) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*TestSignUpSignUpAvailableWorkspacesAndAccessTokens
		graphql.NoUnmarshalJSON
	}
	firstPass.TestSignUpSignUpAvailableWorkspacesAndAccessTokens = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.BootstrapAccess)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalTestSignUpSignUpAvailableWorkspacesAndAccessTokens struct {
	Tokens BootstrapAccessTokensAuthTokenPair `json:"tokens"`

	AvailableWorkspaces BootstrapAccessAvailableWorkspaces `json:"availableWorkspaces"`
}

func (v *TestSignUpSignUpAvailableWorkspacesAndAccessTokens) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *TestSignUpSignUpAvailableWorkspacesAndAccessTokens) __premarshalJSON() (*__premarshalTestSignUpSignUpAvailableWorkspacesAndAccessTokens, error) {
	var retval __premarshalTestSignUpSignUpAvailableWorkspacesAndAccessTokens

	retval.Tokens = v.BootstrapAccess.Tokens
	retval.AvailableWorkspaces = v.BootstrapAccess.AvailableWorkspaces
	return &retval, nil
}

// TestVerifyEmailResponse is returned by TestVerifyEmail on success.
type TestVerifyEmailResponse struct {
	VerifyEmailAndGetWorkspaceAgnosticToken TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens `json:"verifyEmailAndGetWorkspaceAgnosticToken"`
}

// GetVerifyEmailAndGetWorkspaceAgnosticToken returns TestVerifyEmailResponse.VerifyEmailAndGetWorkspaceAgnosticToken, and is useful for accessing the field via an interface.
func (v *TestVerifyEmailResponse) GetVerifyEmailAndGetWorkspaceAgnosticToken() TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens {
	return v.VerifyEmailAndGetWorkspaceAgnosticToken
}

// TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens includes the requested fields of the GraphQL type AvailableWorkspacesAndAccessTokens.
type TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens struct {
	BootstrapAccess `json:"-"`
}

// GetTokens returns TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens.Tokens, and is useful for accessing the field via an interface.
func (v *TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens) GetTokens() BootstrapAccessTokensAuthTokenPair {
	return v.BootstrapAccess.Tokens
}

// GetAvailableWorkspaces returns TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens.AvailableWorkspaces, and is useful for accessing the field via an interface.
func (v *TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens) GetAvailableWorkspaces() BootstrapAccessAvailableWorkspaces {
	return v.BootstrapAccess.AvailableWorkspaces
}

func (v *TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens
		graphql.NoUnmarshalJSON
	}
	firstPass.TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.BootstrapAccess)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalTestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens struct {
	Tokens BootstrapAccessTokensAuthTokenPair `json:"tokens"`

	AvailableWorkspaces BootstrapAccessAvailableWorkspaces `json:"availableWorkspaces"`
}

func (v *TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *TestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens) __premarshalJSON() (*__premarshalTestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens, error) {
	var retval __premarshalTestVerifyEmailVerifyEmailAndGetWorkspaceAgnosticTokenAvailableWorkspacesAndAccessTokens

	retval.Tokens = v.BootstrapAccess.Tokens
	retval.AvailableWorkspaces = v.BootstrapAccess.AvailableWorkspaces
	return &retval, nil
}

type WorkspaceActivationStatus string

const (
	WorkspaceActivationStatusOngoingCreation WorkspaceActivationStatus = "ONGOING_CREATION"
	WorkspaceActivationStatusPendingCreation WorkspaceActivationStatus = "PENDING_CREATION"
	WorkspaceActivationStatusCreated         WorkspaceActivationStatus = "CREATED"
	WorkspaceActivationStatusActive          WorkspaceActivationStatus = "ACTIVE"
	WorkspaceActivationStatusInactive        WorkspaceActivationStatus = "INACTIVE"
	WorkspaceActivationStatusSuspended       WorkspaceActivationStatus = "SUSPENDED"
)

var AllWorkspaceActivationStatus = []WorkspaceActivationStatus{
	WorkspaceActivationStatusOngoingCreation,
	WorkspaceActivationStatusPendingCreation,
	WorkspaceActivationStatusCreated,
	WorkspaceActivationStatusActive,
	WorkspaceActivationStatusInactive,
	WorkspaceActivationStatusSuspended,
}

// __TestActivateWorkspaceInput is used internally by genqlient
type __TestActivateWorkspaceInput struct {
	Data ActivateWorkspaceInput `json:"data"`
}

// GetData returns __TestActivateWorkspaceInput.Data, and is useful for accessing the field via an interface.
func (v *__TestActivateWorkspaceInput) GetData() ActivateWorkspaceInput { return v.Data }

// __TestCreateWorkspaceInput is used internally by genqlient
type __TestCreateWorkspaceInput struct {
	Input SignUpInNewWorkspaceInput `json:"input"`
}

// GetInput returns __TestCreateWorkspaceInput.Input, and is useful for accessing the field via an interface.
func (v *__TestCreateWorkspaceInput) GetInput() SignUpInNewWorkspaceInput { return v.Input }

// __TestJoinWorkspaceInput is used internally by genqlient
type __TestJoinWorkspaceInput struct {
	Email                        string                    `json:"email"`
	Password                     string                    `json:"password"`
	WorkspaceId                  nullable.Nullable[string] `json:"workspaceId,omitempty"`
	WorkspaceInviteHash          nullable.Nullable[string] `json:"workspaceInviteHash,omitempty"`
	WorkspacePersonalInviteToken nullable.Nullable[string] `json:"workspacePersonalInviteToken,omitempty"`
	CaptchaToken                 nullable.Nullable[string] `json:"captchaToken,omitempty"`
	Locale                       nullable.Nullable[string] `json:"locale,omitempty"`
	VerifyEmailRedirectPath      nullable.Nullable[string] `json:"verifyEmailRedirectPath,omitempty"`
}

// GetEmail returns __TestJoinWorkspaceInput.Email, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetEmail() string { return v.Email }

// GetPassword returns __TestJoinWorkspaceInput.Password, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetPassword() string { return v.Password }

// GetWorkspaceId returns __TestJoinWorkspaceInput.WorkspaceId, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetWorkspaceId() nullable.Nullable[string] { return v.WorkspaceId }

// GetWorkspaceInviteHash returns __TestJoinWorkspaceInput.WorkspaceInviteHash, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetWorkspaceInviteHash() nullable.Nullable[string] {
	return v.WorkspaceInviteHash
}

// GetWorkspacePersonalInviteToken returns __TestJoinWorkspaceInput.WorkspacePersonalInviteToken, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetWorkspacePersonalInviteToken() nullable.Nullable[string] {
	return v.WorkspacePersonalInviteToken
}

// GetCaptchaToken returns __TestJoinWorkspaceInput.CaptchaToken, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetCaptchaToken() nullable.Nullable[string] { return v.CaptchaToken }

// GetLocale returns __TestJoinWorkspaceInput.Locale, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetLocale() nullable.Nullable[string] { return v.Locale }

// GetVerifyEmailRedirectPath returns __TestJoinWorkspaceInput.VerifyEmailRedirectPath, and is useful for accessing the field via an interface.
func (v *__TestJoinWorkspaceInput) GetVerifyEmailRedirectPath() nullable.Nullable[string] {
	return v.VerifyEmailRedirectPath
}

// __TestSignUpInput is used internally by genqlient
type __TestSignUpInput struct {
	Email                   string                    `json:"email"`
	Password                string                    `json:"password"`
	CaptchaToken            nullable.Nullable[string] `json:"captchaToken,omitempty"`
	Locale                  nullable.Nullable[string] `json:"locale,omitempty"`
	VerifyEmailRedirectPath nullable.Nullable[string] `json:"verifyEmailRedirectPath,omitempty"`
}

// GetEmail returns __TestSignUpInput.Email, and is useful for accessing the field via an interface.
func (v *__TestSignUpInput) GetEmail() string { return v.Email }

// GetPassword returns __TestSignUpInput.Password, and is useful for accessing the field via an interface.
func (v *__TestSignUpInput) GetPassword() string { return v.Password }

// GetCaptchaToken returns __TestSignUpInput.CaptchaToken, and is useful for accessing the field via an interface.
func (v *__TestSignUpInput) GetCaptchaToken() nullable.Nullable[string] { return v.CaptchaToken }

// GetLocale returns __TestSignUpInput.Locale, and is useful for accessing the field via an interface.
func (v *__TestSignUpInput) GetLocale() nullable.Nullable[string] { return v.Locale }

// GetVerifyEmailRedirectPath returns __TestSignUpInput.VerifyEmailRedirectPath, and is useful for accessing the field via an interface.
func (v *__TestSignUpInput) GetVerifyEmailRedirectPath() nullable.Nullable[string] {
	return v.VerifyEmailRedirectPath
}

// __TestVerifyEmailInput is used internally by genqlient
type __TestVerifyEmailInput struct {
	EmailVerificationToken string                    `json:"emailVerificationToken"`
	Email                  string                    `json:"email"`
	CaptchaToken           nullable.Nullable[string] `json:"captchaToken,omitempty"`
}

// GetEmailVerificationToken returns __TestVerifyEmailInput.EmailVerificationToken, and is useful for accessing the field via an interface.
func (v *__TestVerifyEmailInput) GetEmailVerificationToken() string { return v.EmailVerificationToken }

// GetEmail returns __TestVerifyEmailInput.Email, and is useful for accessing the field via an interface.
func (v *__TestVerifyEmailInput) GetEmail() string { return v.Email }

// GetCaptchaToken returns __TestVerifyEmailInput.CaptchaToken, and is useful for accessing the field via an interface.
func (v *__TestVerifyEmailInput) GetCaptchaToken() nullable.Nullable[string] { return v.CaptchaToken }

// The mutation executed by TestActivateWorkspace.
const TestActivateWorkspace_Operation = `
mutation TestActivateWorkspace ($data: ActivateWorkspaceInput!) {
	activateWorkspace(data: $data) {
		id
		displayName
		activationStatus
	}
}
`

// Use data: {}. The legacy displayName input is ignored by the resolver.
func TestActivateWorkspace(
	ctx_ context.Context,
	client_ graphql.Client,
	data ActivateWorkspaceInput,
) (data_ *TestActivateWorkspaceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TestActivateWorkspace",
		Query:  TestActivateWorkspace_Operation,
		Variables: &__TestActivateWorkspaceInput{
			Data: data,
		},
	}

	data_ = &TestActivateWorkspaceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by TestCreateWorkspace.
const TestCreateWorkspace_Operation = `
mutation TestCreateWorkspace ($input: SignUpInNewWorkspaceInput!) {
	signUpInNewWorkspace(input: $input) {
		... BootstrapWorkspace
	}
}
fragment BootstrapWorkspace on SignUp {
	loginToken {
		... BootstrapToken
	}
	workspace {
		id
		workspaceUrls {
			customUrl
			subdomainUrl
		}
	}
}
fragment BootstrapToken on AuthToken {
	token
	expiresAt
}
`

// Service requires nonblank displayName even though SDL marks it optional.
func TestCreateWorkspace(
	ctx_ context.Context,
	client_ graphql.Client,
	input SignUpInNewWorkspaceInput,
) (data_ *TestCreateWorkspaceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TestCreateWorkspace",
		Query:  TestCreateWorkspace_Operation,
		Variables: &__TestCreateWorkspaceInput{
			Input: input,
		},
	}

	data_ = &TestCreateWorkspaceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by TestJoinWorkspace.
const TestJoinWorkspace_Operation = `
mutation TestJoinWorkspace ($email: String!, $password: String!, $workspaceId: UUID, $workspaceInviteHash: String, $workspacePersonalInviteToken: String, $captchaToken: String, $locale: String, $verifyEmailRedirectPath: String) {
	signUpInWorkspace(email: $email, password: $password, workspaceId: $workspaceId, workspaceInviteHash: $workspaceInviteHash, workspacePersonalInviteToken: $workspacePersonalInviteToken, captchaToken: $captchaToken, locale: $locale, verifyEmailRedirectPath: $verifyEmailRedirectPath) {
		... BootstrapWorkspace
	}
}
fragment BootstrapWorkspace on SignUp {
	loginToken {
		... BootstrapToken
	}
	workspace {
		id
		workspaceUrls {
			customUrl
			subdomainUrl
		}
	}
}
fragment BootstrapToken on AuthToken {
	token
	expiresAt
}
`

// Personal invitation token comes from the disposable stack's mail sink.
// Always specify the intended workspace/invitation, never implicit new-workspace
// signup. Establish an independent recovery administrator via an admin invite.
func TestJoinWorkspace(
	ctx_ context.Context,
	client_ graphql.Client,
	email string,
	password string,
	workspaceId nullable.Nullable[string],
	workspaceInviteHash nullable.Nullable[string],
	workspacePersonalInviteToken nullable.Nullable[string],
	captchaToken nullable.Nullable[string],
	locale nullable.Nullable[string],
	verifyEmailRedirectPath nullable.Nullable[string],
) (data_ *TestJoinWorkspaceResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TestJoinWorkspace",
		Query:  TestJoinWorkspace_Operation,
		Variables: &__TestJoinWorkspaceInput{
			Email:                        email,
			Password:                     password,
			WorkspaceId:                  workspaceId,
			WorkspaceInviteHash:          workspaceInviteHash,
			WorkspacePersonalInviteToken: workspacePersonalInviteToken,
			CaptchaToken:                 captchaToken,
			Locale:                       locale,
			VerifyEmailRedirectPath:      verifyEmailRedirectPath,
		},
	}

	data_ = &TestJoinWorkspaceResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by TestSignUp.
const TestSignUp_Operation = `
mutation TestSignUp ($email: String!, $password: String!, $captchaToken: String, $locale: String, $verifyEmailRedirectPath: String) {
	signUp(email: $email, password: $password, captchaToken: $captchaToken, locale: $locale, verifyEmailRedirectPath: $verifyEmailRedirectPath) {
		... BootstrapAccess
	}
}
fragment BootstrapAccess on AvailableWorkspacesAndAccessTokens {
	tokens {
		accessOrWorkspaceAgnosticToken {
			... BootstrapToken
		}
		refreshToken {
			... BootstrapToken
		}
	}
	availableWorkspaces {
		availableWorkspacesForSignIn {
			id
			displayName
			workspaceUrls {
				customUrl
				subdomainUrl
			}
		}
		availableWorkspacesForSignUp {
			id
			displayName
			workspaceUrls {
				customUrl
				subdomainUrl
			}
		}
	}
}
fragment BootstrapToken on AuthToken {
	token
	expiresAt
}
`

func TestSignUp(
	ctx_ context.Context,
	client_ graphql.Client,
	email string,
	password string,
	captchaToken nullable.Nullable[string],
	locale nullable.Nullable[string],
	verifyEmailRedirectPath nullable.Nullable[string],
) (data_ *TestSignUpResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TestSignUp",
		Query:  TestSignUp_Operation,
		Variables: &__TestSignUpInput{
			Email:                   email,
			Password:                password,
			CaptchaToken:            captchaToken,
			Locale:                  locale,
			VerifyEmailRedirectPath: verifyEmailRedirectPath,
		},
	}

	data_ = &TestSignUpResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by TestVerifyEmail.
const TestVerifyEmail_Operation = `
mutation TestVerifyEmail ($emailVerificationToken: String!, $email: String!, $captchaToken: String) {
	verifyEmailAndGetWorkspaceAgnosticToken(emailVerificationToken: $emailVerificationToken, email: $email, captchaToken: $captchaToken) {
		... BootstrapAccess
	}
}
fragment BootstrapAccess on AvailableWorkspacesAndAccessTokens {
	tokens {
		accessOrWorkspaceAgnosticToken {
			... BootstrapToken
		}
		refreshToken {
			... BootstrapToken
		}
	}
	availableWorkspaces {
		availableWorkspacesForSignIn {
			id
			displayName
			workspaceUrls {
				customUrl
				subdomainUrl
			}
		}
		availableWorkspacesForSignUp {
			id
			displayName
			workspaceUrls {
				customUrl
				subdomainUrl
			}
		}
	}
}
fragment BootstrapToken on AuthToken {
	token
	expiresAt
}
`

// Verification token must come from the disposable stack's mail sink.
func TestVerifyEmail(
	ctx_ context.Context,
	client_ graphql.Client,
	emailVerificationToken string,
	email string,
	captchaToken nullable.Nullable[string],
) (data_ *TestVerifyEmailResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TestVerifyEmail",
		Query:  TestVerifyEmail_Operation,
		Variables: &__TestVerifyEmailInput{
			EmailVerificationToken: emailVerificationToken,
			Email:                  email,
			CaptchaToken:           captchaToken,
		},
	}

	data_ = &TestVerifyEmailResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
